import { ReactNode } from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function DashboardLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      DASHBOARD HEADER
      <body>{children}</body>
    </html>
  )
}
